#!/usr/bin/env bash
# Start a tmux session and run a batch of commands, each in a separate window.
# Use byobu if available, or tmux by default.

# commands=("python -i")
command="python -i"
session="Experiments"

# echo ${commands[1]}
# tmux attach-session -t $session \; byobu new-window -n "$window" \; send-keys -t $session:"$window" "${commands[1]}" C-m
if [[ $(command -v byobu) ]]; then
    multiplexer=byobu
else
    multiplexer=tmux
fi

echo "Using $multiplexer"

$multiplexer new-session -d -s $session 2> /dev/null || echo "Session $session already exists."

for parameter in "11" "22"; do
    window="$parameter"
    command_with_parameter="$command /home/adam/Tests/approx_pi_montecarlo.py $parameter "
    $multiplexer new-window -t "$session" -n "$window" -- $command_with_parameter;
    echo "$session:$window <- $command_with_parameter"
done



