#!/usr/bin/env bash
# Start a tmux session and run a batch of commands, each in a separate window.
# Use byobu if available, or tmux by default.

COMMAND="python -i /home/adam/Tests/approx_pi_montecarlo.py"
SESSION="Experiments"
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
	-n|--name)
	    SESSION=$2
	    shift
	    shift
	    ;;
	-c|--command)
	    COMMAND=$2
	    shift
	    shift
	    ;;
	-*|--*)
	    echo "Unknown option $1"
	    exit 1
	    ;;
	*)
	    POSITIONAL_ARGS+=("$1")
	    shift
	    ;;
    esac
done

if [[ $(command -v byobu) ]]; then
    MULTIPLEXER=byobu
else
    MULTIPLEXER=tmux
fi

echo "Using $MULTIPLEXER"

$MULTIPLEXER new-session -d -s $SESSION 2> /dev/null || echo "Session $SESSION already exists."

for PARAMETER in ${POSITIONAL_ARGS[@]}; do
    WINDOW="$PARAMETER"
    COMMAND_WITH_PARAMETER="$COMMAND $PARAMETER "
    $MULTIPLEXER new-window -t "$SESSION" -n "$WINDOW" -- $COMMAND_WITH_PARAMETER;
    echo "$SESSION:$WINDOW <- $COMMAND_WITH_PARAMETER"
done



