#!/usr/bin/env bash
# Generate the TAGS file for a python project given
# Argument: path to the project (defaults to $(pwd))

PROJECT_PATH=""
while [[ $# -gt 0 ]]; do
    case $1 in
	*)
	    PROJECT_PATH=$1
	    break
	    ;;
    esac
done

if [[ -n $PROJECT_PATH && -d $PROJECT_PATH ]]; then
    find $PROJECT_PATH -name "*.py" | etags -o $PROJECT_PATH/TAGS -
else
    echo "Project path \"$PROJECT_PATH\" was not set or is not a directory." 
    exit
fi
